### ISSUE TITLE
Discussion: Copying events

### ISSUE THREAD

**Issue by kristoferjoseph** [maxogden/yo-yo#50]
This is a spill over issue from a discussion that started in #44 

The gist of the discussion is that it would be nice to not have to loop over an array of events that are commonly set as attributes on an element i.e. `onclick` etc. 

Main downside is that this list is not a complete list and it can impact perf if that list grows to encompass **all** possible events that can be set as attributes.

Users can already pass in an options object with an events key specifying what events they are using, which imho seems like a pretty decent solution. 

Failing that we fallback to the slower approach of looping over an incomplete list of "common" events and check to see if they need to be copied over.

Otherwise we find some way to intelligently copy **only** the events that are set as attributes.

**Comment by tbranyen** [comment]
This might be super hacky, but you could also check if the function is the same (not reference, but contents) via a `Function#toString` comparison.

**Comment by kristoferjoseph** [comment]
Interesting. Yes. That would happen after this step of finding /on^/ attributes though if I am understanding correctly.

**Comment by tbranyen** [comment]
Yeah, and thinking about this more there's lots of holes with this approach. Since two methods could look the same but refer to very difference references.

**Comment by kristoferjoseph** [comment]
Right. Have run into this problem before when using a similar approach to generate an ID by hashing a function.toString. Works, unless you want multiple instances.

**Comment by aknuds1** [comment]
I'm having issues with yo-yo not updating event listeners for elements generated by hyperscript, for example when changing the `onclick` handler the second time an element is rendered.

With the following example, `Click handler 1` will be printed, as the old event handler will still be part of the updated object returned by `yo.update`:

    const yo = require('yo-yo')
    const h = require('hyperscript')

    const div1 = h('div', {onclick: () => {console.log('Click handler 1')}})
    const div2 = h('div', {onclick: () => {console.log('Click handler 2')}})

    const updated = yo.update(div1, div2)
    updated.click() // Prints 'Click handler 1'
                   
What I've found through debugging, is that hyperscript sets event handlers via [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener), whereas yo-yo expects them to be set via attributes such as `onclick`. Is this by design?
